### ISSUE TITLE
Need intl: ^0.18.0 which is the latest version to be compatible with other libs.

### ISSUE THREAD

**Issue by BobFactory** [a7mdragab/date_only_field#1]
Hi, 
I wanted to use this package but `pub get` fails because most of the packages I am using are dependent on  `intl: ^0.18.0`. 

The official version for intl is `intl: ^0.18.1`. Can we please upgrade the version so this package becomes compatible with other packages?

Thanks in advance for the package.

**Comment by a7mdragab** [comment]
Thanks for notice.
Fixed and updated ``date_only_field: ^0.0.14``
Good luck
